# Generated by Django 4.0.3 on 2022-04-13 21:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinicName', models.CharField(blank=True, max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(default='Moh', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('medicattions', models.BooleanField(default=False, null=True)),
                ('med_text', models.TextField(blank=True, null=True)),
                ('allergies', models.BooleanField(default=False, null=True)),
                ('allergies_text', models.TextField(blank=True, null=True)),
                ('E_firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('E_lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('E_contactNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('clinic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.clinic')),
                ('doctor', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('todayvisit', models.DateField(default=datetime.datetime.now)),
                ('nextvisit', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('med_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.operation')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.room')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalBalance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pendingBalance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('AmountDue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.clinic')),
                ('journal_entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.journalentrytype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.patient')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.room'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=500, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(default='Moh', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(default='Tooth Extraction', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.operation')),
                ('room', models.ForeignKey(default='Operation', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.room')),
            ],
        ),
    ]
