# Generated by Django 4.0.4 on 2022-04-29 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('E_firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('E_lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('E_contactNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('todayvisit', models.DateField(default=datetime.datetime.now)),
                ('nextvisit', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('med_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.operation')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentJournal',
            fields=[
                ('totalBalance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pendingBalance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.patient')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.room'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 4, 29, 8, 26, 15, 891317, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2022, 4, 29, 8, 26, 15, 891317, tzinfo=utc))),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('operation', models.ForeignKey(default='Tooth Extraction', on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.operation')),
            ],
        ),
    ]
