# Generated by Django 4.0.3 on 2022-04-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='operation',
            field=models.ForeignKey(default='Tooth Extraction', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctordashboard.operation'),
        ),
    ]
