# Generated by Django 4.0.1 on 2022-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
