# Generated by Django 4.0.3 on 2022-04-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0003_alter_patient_user_alter_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
