# Generated by Django 4.0.4 on 2022-04-29 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0003_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='nextvisit',
            new_name='visitdate',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='med_text',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='todayvisit',
        ),
        migrations.AddField(
            model_name='visit',
            name='medicaments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 12, 49, 8, 523020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 29, 12, 49, 8, 523020, tzinfo=utc)),
        ),
    ]
