# Generated by Django 4.0.3 on 2022-04-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0003_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='paymentjournal',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='clinic',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
