# Generated by Django 4.0.3 on 2022-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0004_remove_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
