# Generated by Django 4.0.4 on 2022-04-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0004_remove_operation_clinic_remove_paymentjournal_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicattions',
        ),
    ]
