# Generated by Django 4.0.3 on 2022-04-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0005_operation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
