# Generated by Django 4.0.4 on 2022-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0006_remove_room_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
    ]
