# Generated by Django 4.0.3 on 2022-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0006_alter_operation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
