# Generated by Django 4.0.4 on 2022-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0007_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
